### ISSUE TITLE
Support for logs to be sent as separate entity, not same as tags

### ISSUE THREAD

**Issue by ashishmahi** [DanielMSchmidt/zipkin-javascript-opentracing#102]
We already have method SetTag which add tags as key value and send it back to collector. I found that you have log method which rather than logging message string sends them as tag which i found is wrong. one way we already have a method which can add tags so log should be doing actual logging.. not adding tags again. that way library will have both way to add tags and add logs separately. however i found that the core tracer which you are using here has already method to log separately. the method is recordMessage. so if you can use that when log is being called, then you would have support for logs as well. 

I'll anyway raise PR for it. but you can comment here your thoughts.

**Comment by ashishmahi** [comment]
@DanielMSchmidt  this is the PR.
https://github.com/DanielMSchmidt/zipkin-javascript-opentracing/pull/103

Please help me merging it to  master so that it can have ability to send logs separately to backend. 
waiting for your Review and feedback if any

**Comment by DanielMSchmidt** [comment]
Solved in [`3.0.0`](https://github.com/DanielMSchmidt/zipkin-javascript-opentracing/releases/tag/v3.0.0)
