### ISSUE TITLE
Is "kind" only set per tracer, globally?

### ISSUE THREAD

**Issue by vitalif** [DanielMSchmidt/zipkin-javascript-opentracing#49]
Hi,
I'm testing your module in one of our "API gateways", acting like "smart HTTP proxies", and I'm curious if it's possible to log some spans as server and some spans as client?
As I understand now the "kind" option is only set per tracer object, so HTTP requests the api gateway is making itself are also marked as "server". But they should be marked as "client".
Is it currently possible?

**Comment by vitalif** [comment]
So it is ok to create spans in one tracer as children of other tracer's spans?

**Comment by DanielMSchmidt** [comment]
Yeah, I think so. Would you mind doing a PR for that to the docs? Maybe in a FAQ section, so that others have an easier time understating this?

**Comment by vitalif** [comment]
I think I'll first try it in code

**Comment by vitalif** [comment]
It's strange but it seems it works...:)

**Comment by DanielMSchmidt** [comment]
Great, could you add something to the readme? Also, why is it strange to you?

**Comment by DanielMSchmidt** [comment]
Closed due to inactivity
