### ISSUE TITLE
Sampler rate for tracer

### ISSUE THREAD

**Issue by ikc89** [DanielMSchmidt/zipkin-javascript-opentracing#56]
Hello,

I am using this library in a react project and i am trying to work it in client side. But i can not apply sampler rate for my requests. When i am searching for the library i see these lines.

```
this._zipkinTracer = new Tracer({
      ctxImpl: new ExplicitContext(),
      recorder: options.recorder
    });
    this._Span = SpanCreator({
      tracer: this._zipkinTracer,
      serviceName: this._serviceName,
      kind: options.kind,
      sampler: options.sampler
    });
```

Here, sampler is only applied for span, not for tracer. Why ?

Thanks for your help.

Kerim

**Comment by DanielMSchmidt** [comment]
Closed due to inactivity
