### ISSUE TITLE
OpenTracing does not support tag?

### ISSUE THREAD

**Issue by Moocar** [DanielMSchmidt/zipkin-javascript-opentracing#67]
I just plugged this library into our project and noticed that it [raises an error](https://github.com/DanielMSchmidt/zipkin-javascript-opentracing/blob/master/src/index.js#L136) when setTags is called with a tag not contained within [opentracing etx/tags.ts](https://github.com/opentracing/opentracing-javascript/blob/master/src/ext/tags.ts). From my understanding of the [open tracing docs](https://opentracing-javascript.surge.sh/classes/span.html#addtags), tags can be arbitrary `string/any` pairs. Why the enforcement?

**Comment by DanielMSchmidt** [comment]
You seem to be right there, I understood it as "only these tags". Would you like to do a PR to remove the error check?

**Comment by Moocar** [comment]
Cool! I'm evaluating a few different approaches to getting tracing working in out application. If we go down the opentracing-zipkin path, I'll definitely submit a PR.

**Comment by DanielMSchmidt** [comment]
That sounds great, I would really appreciate if you could keep me posted :)

**Comment by florianrusch** [comment]
This issue can be closed or? @DanielMSchmidt @Moocar

**Comment by Moocar** [comment]
@florianrusch It was a while ago, but my PR was merged, so I'm going to assume it's solved. Closing :)
