### ISSUE TITLE
Support for `Span.context()`

### ISSUE THREAD

**Issue by antoinetissier** [DanielMSchmidt/zipkin-javascript-opentracing#98]
Hi,

Method [`span.context()`](https://opentracing-javascript.surge.sh/classes/span.html#context) from the OpenTracing API reference does not seem to be supported. Is there any plan on supporting it anytime soon ?

The goal ultimately is to use it to get the span's id and trace id through `span.context().toSpanId()` and `span.context().toTraceId()`. Is there maybe another way to get them ?

Thanks a lot,
Antoine

**Comment by DanielMSchmidt** [comment]
Feel free to add a PR for this 👍

**Comment by antoinetissier** [comment]
Here it is :) https://github.com/DanielMSchmidt/zipkin-javascript-opentracing/pull/100

**Comment by DanielMSchmidt** [comment]
Released in https://github.com/DanielMSchmidt/zipkin-javascript-opentracing/releases/tag/v2.1.0
